name: Pear build
run-name: build go
on: 
  push:
    paths:
      - pear/**
  workflow_dispatch:

jobs:
  go-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
         go-version: 1.18
      - run: |
          cd pear
          go build .
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: go dist
          path: |
            pear/hw*

